import type { Workflow } from './types'

export const WORKFLOW_TEMPLATES: Omit<Workflow, 'id' | 'createdAt' | 'updatedAt' | 'executions' | 'runCount' | 'successCount'>[] = [
  {
    name:        'Salary Auto-Processing',
    description: 'When a salary slip is uploaded, automatically sync income, calculate tithe, update accounts, and refresh the dashboard.',
    icon:        '💰',
    category:    'income',
    status:      'active',
    isTemplate:  true,
    lastRun:     undefined,
    trigger: {
      type:      'event',
      eventType: 'salary.received',
    },
    conditions: [],
    actions: [
      { id: 'a1', type: 'sync_module', label: 'Sync to Income',    config: { module: 'income'    }, retries: 2 },
      { id: 'a2', type: 'sync_module', label: 'Update Accounts',   config: { module: 'accounts'  }, retries: 2 },
      { id: 'a3', type: 'sync_module', label: 'Update Taxes',      config: { module: 'taxes'     }, retries: 1 },
      { id: 'a4', type: 'update_goal', label: 'Contribute to Tithe', config: { pct: 10          }, retries: 1 },
      { id: 'a5', type: 'recalculate', label: 'Refresh Dashboard', config: { paths: ['/dashboard'] }, retries: 1 },
    ],
  },
  {
    name:        'Bill Due Reminder',
    description: 'Send a notification 3 days before any EMI or insurance renewal is due.',
    icon:        '📅',
    category:    'alerts',
    status:      'active',
    isTemplate:  true,
    lastRun:     undefined,
    trigger: { type: 'event', eventType: 'debt.payment_due' },
    conditions: [
      { field: 'event.payload.daysLeft', operator: '<=', value: 3, label: 'Due within 3 days' },
    ],
    actions: [
      { id: 'a1', type: 'notify', label: 'Send EMI reminder notification',
        config: { title: 'EMI Due Soon', message: 'Your {lender} EMI of ₹{amount} is due in {daysLeft} days' },
        retries: 3 },
    ],
  },
  {
    name:        'SIP Investment Reminder',
    description: 'Remind you to set up or review your SIP on the 1st of every month.',
    icon:        '📈',
    category:    'investments',
    status:      'active',
    isTemplate:  true,
    lastRun:     undefined,
    trigger: { type: 'schedule', schedule: 'monthly' },
    conditions: [],
    actions: [
      { id: 'a1', type: 'notify',      label: 'SIP check notification',
        config: { title: 'SIP Review', message: 'Review your SIP investments for this month' },
        retries: 2 },
      { id: 'a2', type: 'trigger_ai',  label: 'AI portfolio analysis',
        config: { prompt: 'Analyse my current investment portfolio and suggest SIP adjustments' },
        retries: 1 },
    ],
  },
  {
    name:        'Budget Exceeded Alert',
    description: 'Alert when monthly expenses cross 80% of estimated monthly income.',
    icon:        '⚠️',
    category:    'expenses',
    status:      'active',
    isTemplate:  true,
    lastRun:     undefined,
    trigger: { type: 'event', eventType: 'budget.exceeded' },
    conditions: [
      { field: 'event.payload.spentPct', operator: '>=', value: 80, label: 'Spent ≥ 80% of budget' },
    ],
    actions: [
      { id: 'a1', type: 'notify', label: 'Budget alert notification',
        config: { title: 'Budget Warning', message: 'You have spent {spentPct}% of your monthly budget' },
        retries: 3 },
      { id: 'a2', type: 'flag_review', label: 'Flag top expense categories',
        config: { module: 'expenses' }, retries: 1 },
    ],
  },
  {
    name:        'Insurance Renewal Tracker',
    description: 'Notify 30 days before any insurance policy renewal and add it to the calendar.',
    icon:        '🛡️',
    category:    'insurance',
    status:      'active',
    isTemplate:  true,
    lastRun:     undefined,
    trigger: { type: 'event', eventType: 'insurance.renewal_due' },
    conditions: [
      { field: 'event.payload.daysLeft', operator: '<=', value: 30, label: 'Due within 30 days' },
    ],
    actions: [
      { id: 'a1', type: 'notify',      label: 'Renewal notification',
        config: { title: 'Insurance Renewal', message: '{policyName} renews in {daysLeft} days — ₹{premium}' },
        retries: 3 },
      { id: 'a2', type: 'sync_module', label: 'Add to Calendar',
        config: { module: 'calendar' }, retries: 1 },
    ],
  },
  {
    name:        'Tax Document Auto-Filing',
    description: 'When a Form 16, Form 26AS, or AIS is uploaded, extract data and update Tax Centre.',
    icon:        '📋',
    category:    'taxes',
    status:      'active',
    isTemplate:  true,
    lastRun:     undefined,
    trigger: { type: 'event', eventType: 'tax.document_processed' },
    conditions: [],
    actions: [
      { id: 'a1', type: 'sync_module', label: 'Update Tax Centre',
        config: { module: 'taxes' }, retries: 2 },
      { id: 'a2', type: 'recalculate', label: 'Recalculate tax liability',
        config: { paths: ['/taxes', '/dashboard'] }, retries: 1 },
      { id: 'a3', type: 'trigger_ai',  label: 'AI tax saving suggestions',
        config: { prompt: 'Based on my income and TDS, suggest tax saving investments under 80C and 80D' },
        retries: 1 },
    ],
  },
  {
    name:        'Goal Milestone Celebration',
    description: 'Notify when a financial goal reaches 25%, 50%, 75%, or 100% completion.',
    icon:        '🎯',
    category:    'goals',
    status:      'active',
    isTemplate:  true,
    lastRun:     undefined,
    trigger: { type: 'event', eventType: 'goal.milestone' },
    conditions: [],
    actions: [
      { id: 'a1', type: 'notify', label: 'Milestone notification',
        config: { title: 'Goal Milestone!', message: 'Your goal "{goalName}" is {pct}% complete!' },
        retries: 2 },
      { id: 'a2', type: 'recalculate', label: 'Refresh dashboard health score',
        config: { paths: ['/dashboard'] }, retries: 1 },
    ],
  },
  {
    name:        'Low Balance Warning',
    description: 'Alert when any bank account balance drops below ₹5,000.',
    icon:        '🏦',
    category:    'alerts',
    status:      'active',
    isTemplate:  true,
    lastRun:     undefined,
    trigger: { type: 'event', eventType: 'account.balance_low' },
    conditions: [
      { field: 'event.payload.balance', operator: '<', value: 5000, label: 'Balance < ₹5,000' },
    ],
    actions: [
      { id: 'a1', type: 'notify', label: 'Low balance alert',
        config: { title: 'Low Balance Alert', message: '{accountName} balance is ₹{balance} — below ₹5,000' },
        retries: 3 },
    ],
  },
  {
    name:        'Tithe Monthly Reminder',
    description: 'Remind to record tithe on the 1st of every month based on net income.',
    icon:        '🙏',
    category:    'income',
    status:      'active',
    isTemplate:  true,
    lastRun:     undefined,
    trigger: { type: 'event', eventType: 'tithe.due' },
    conditions: [],
    actions: [
      { id: 'a1', type: 'notify', label: 'Tithe reminder',
        config: { title: 'Tithe Due', message: 'Monthly tithe of ₹{amount} (10% of ₹{income}) is due' },
        retries: 2 },
    ],
  },
  {
    name:        'Portfolio Rebalance Alert',
    description: 'Alert when portfolio allocation drifts more than 10% from target.',
    icon:        '⚖️',
    category:    'investments',
    status:      'draft',
    isTemplate:  true,
    lastRun:     undefined,
    trigger: { type: 'event', eventType: 'portfolio.rebalance_due' },
    conditions: [
      { field: 'event.payload.drift', operator: '>', value: 10, label: 'Drift > 10%' },
    ],
    actions: [
      { id: 'a1', type: 'notify',     label: 'Rebalance alert',
        config: { title: 'Portfolio Rebalance', message: 'Your portfolio has drifted {drift}% from target allocation' },
        retries: 2 },
      { id: 'a2', type: 'trigger_ai', label: 'AI rebalancing suggestions',
        config: { prompt: 'My portfolio has drifted from target. Suggest rebalancing actions.' },
        retries: 1 },
    ],
  },
]

// Build full Workflow objects with generated IDs
export const BUILT_IN_WORKFLOWS: Workflow[] = WORKFLOW_TEMPLATES.map((t, i) => ({
  ...t,
  id:           `tpl-${i + 1}`,
  createdAt:    new Date().toISOString(),
  updatedAt:    new Date().toISOString(),
  executions:   [],
  runCount:     0,
  successCount: 0,
}))
